Repository inviwo/inviwo, pull requests merged in 2018-06, with the labels that each got.

#150 CLang warn fix about missing override specifier
  include/inviwo/core/datastructures/transferfunction.h
Labels: C: Clang, S: Unix

#154 Core: refactored Clock, ClockGL, closes #48 #49
  include/inviwo/core/util/clock.h
  modules/opengl/clockgl.cpp
  modules/opengl/clockgl.h
  modules/python3qt/pythoneditorwidget.cpp
  src/core/util/clock.cpp
  src/qt/editor/processorgraphicsitem.cpp
Labels: P: OpenGL

#157 Various fixes
  include/inviwo/core/datastructures/geometry/typedmesh.h
  include/inviwo/core/util/clock.h
Labels: C: GCC, S: Unix
