Repository inviwo/inviwo, pull requests merged in 2018-04, with the labels that each got.

#82 ABufferGL: Fixed transparency when using mesh color
  modules/abuffergl/glsl/abuffergeometrygl.frag
Labels: T: Bug

#75 Fix/center camera on geometry
  include/inviwo/core/properties/cameraproperty.h
  modules/base/CMakeLists.txt
  modules/base/algorithm/mesh/axisalignedboundingbox.cpp
  modules/base/algorithm/mesh/axisalignedboundingbox.h
  modules/base/algorithm/mesh/meshcameraalgorithms.cpp
  modules/base/algorithm/mesh/meshcameraalgorithms.h
  modules/basegl/processors/meshrenderprocessorgl.cpp
  modules/basegl/processors/meshrenderprocessorgl.h
  src/core/properties/cameraproperty.cpp
Labels: T: Bug, T: Feature

#88 Feature/tf refactoring
  include/inviwo/core/datastructures/datamapper.h
  include/inviwo/core/datastructures/isovalue.h
  include/inviwo/core/datastructures/isovaluecollection.h
  include/inviwo/core/datastructures/tfprimitive.h
  include/inviwo/core/datastructures/tfprimitiveset.h
  include/inviwo/core/datastructures/transferfunction.h
  include/inviwo/core/datastructures/transferfunctiondatapoint.h
  include/inviwo/core/io/serialization/deserializer.h
  include/inviwo/core/properties/isovalueproperty.h
  include/inviwo/core/properties/transferfunctionproperty.h
  modules/basegl/processors/volumeslicegl.cpp
  modules/opengl/shader/shaderutils.cpp
  modules/qtwidgets/CMakeLists.txt
  modules/qtwidgets/colorwheel.cpp
  modules/qtwidgets/colorwheel.h
  modules/qtwidgets/inviwoqtutils.cpp
  modules/qtwidgets/inviwoqtutils.h
  modules/qtwidgets/properties/isovaluepropertywidgetqt.cpp
  modules/qtwidgets/properties/transferfunctioncontrolpointconnection.cpp
  modules/qtwidgets/properties/transferfunctioncontrolpointconnection.h
  modules/qtwidgets/properties/transferfunctioneditor.cpp
  modules/qtwidgets/properties/transferfunctioneditor.h
  modules/qtwidgets/properties/transferfunctioneditorcontrolpoint.cpp
  modules/qtwidgets/properties/transferfunctioneditorcontrolpoint.h
  modules/qtwidgets/properties/transferfunctioneditorprimitive.cpp
  modules/qtwidgets/properties/transferfunctioneditorprimitive.h
  modules/qtwidgets/properties/transferfunctioneditorview.cpp
  modules/qtwidgets/properties/transferfunctioneditorview.h
  modules/qtwidgets/properties/transferfunctionpropertydialog.cpp
  modules/qtwidgets/properties/transferfunctionpropertydialog.h
  modules/qtwidgets/properties/transferfunctionpropertywidgetqt.cpp
  src/core/CMakeLists.txt
  src/core/datastructures/datamapper.cpp
  src/core/datastructures/isovalue.cpp
  src/core/datastructures/isovaluecollection.cpp
  src/core/datastructures/tfprimitive.cpp
  src/core/datastructures/tfprimitiveset.cpp
  src/core/datastructures/transferfunction.cpp
  src/core/datastructures/transferfunctiondatapoint.cpp
  src/core/properties/isovalueproperty.cpp
  src/core/properties/transferfunctionproperty.cpp
  src/qt/applicationbase/inviwoapplicationqt.cpp
Labels: T: Feature
