Repository inviwo/inviwo, pull requests merged in 2019-08, with the labels that each got.

#614 QT: Fix qt deprecation warnings (using windows qt 5.13.0)
  modules/python3qt/src/pythoneditorwidget.cpp
  modules/python3qt/src/pythonmenu.cpp
  modules/qtwidgets/src/angleradiuswidget.cpp
  modules/qtwidgets/src/codeedit.cpp
  modules/qtwidgets/src/inviwoqtutils.cpp
  modules/qtwidgets/src/properties/texteditorwidgetqt.cpp
  src/qt/editor/fileassociations.cpp
  src/qt/editor/inviwomainwindow.cpp
  src/qt/editor/processorlistwidget.cpp
  src/qt/editor/processorstatusgraphicsitem.cpp
  src/qt/editor/toolsmetamenu.cpp
  src/qt/editor/welcomewidget.cpp
Labels: J: Format Test Failure

#622 c++17
  CHANGELOG.md
  CMakeLists.txt
  README.md
  apps/inviwo/CMakeLists.txt
  cmake/compileoptions.cmake
  cmake/globalconfig.cmake
  cmake/globalmacros.cmake
  cmake/installutils.cmake
  docs/markdown/Index.md
  ext/tiff/CMakeLists.txt
  include/inviwo/core/util/transformiterator.h
  modules/assimp/ext/assimp/CMakeLists.txt
  modules/cimg/CMakeLists.txt
  modules/glfw/CMakeLists.txt
  resources/changelog.html
  src/core/CMakeLists.txt
  tools/meta/CMakeLists.txt
Labels: J: Format Test Failure

#625 Meta: Possible compile fix for MSVC 2019
  tools/meta/include/inviwo/meta/cmake/cmakefile.hpp
  tools/meta/include/inviwo/meta/inviwomodule.hpp
  tools/meta/include/inviwo/meta/inviwomoduleconf.hpp
  tools/meta/src/paths.cpp
Labels: J: Format Test Failure

#624 Core: PropertyPresetManager: Fix for applying present on SerializationMode::None
  src/core/properties/propertypresetmanager.cpp
Labels: J: Format Test Failure

#627 Feature/fix static builds windows
  ext/glm/CMakeLists.txt
  include/inviwo/core/properties/tfpropertyconcept.h
  modules/opengl/ext/glew/CMakeLists.txt
  modules/python3qt/src/pythonmenu.cpp
  modules/qtwidgets/src/codeedit.cpp
  modules/webbrowser/src/renderhandlergl.cpp
  modules/webbrowser/src/webbrowsermodule.cpp
  src/core/properties/tfpropertyconcept.cpp
Labels: C: MSVC, J: Format Test Failure, P: Build System

#626 Better tf image import
  CMakeLists.txt
  cmake/installutils.cmake
  include/inviwo/core/datastructures/transferfunction.h
  include/inviwo/core/util/zip.h
  src/core/datastructures/transferfunction.cpp
Labels: J: Format Test Failure

#630 CMake: Fix for cmake <3.15
  CMakeLists.txt
  cmake/installutils.cmake
  modules/assimp/ext/assimp/CMakeLists.txt
  modules/hdf5/CMakeLists.txt
Labels: J: Format Test Failure

#631 Qt: Make sure resources are loaded/linked when building statically
  modules/qtwidgets/src/qtwidgetsmodule.cpp
Labels: J: Format Test Failure

#636 Python3: export fix
  modules/python3/include/modules/python3/pyutils.h
Labels: J: Format Test Failure

#633 tidds: Fix for correctly enforcing shared building of tidds
  modules/pvm/ext/tidds/CMakeLists.txt
Labels: J: Format Test Failure

#634 Webrowser: CEF_TARGET_OUT_DIR need to be set to the executable path.
  modules/webbrowser/CMakeLists.txt
Labels: J: Format Test Failure

#641 CMake: Correct use of GENERATOR_IS_MULTI_CONFIG property
  cmake/globalconfig.cmake
  modules/webbrowser/CMakeLists.txt
  src/core/CMakeLists.txt
Labels: J: Format Test Failure

#638 Linkfix
  include/inviwo/core/properties/minmaxproperty.h
  include/inviwo/core/properties/ordinalproperty.h
  include/inviwo/core/properties/templateproperty.h
  include/inviwo/core/properties/valuewrapper.h
  modules/hdf5/src/processors/hdf5volumesource.cpp
  modules/plottinggl/include/modules/plottinggl/processors/colorscalelegend.h
  modules/plottinggl/src/processors/colorscalelegend.cpp
  modules/plottinggl/tests/regression/color_scale_legend/Canvas.png
Labels: J: Format Test Failure

#642 Jenkins: doxygen fix
  tools/jenkins/util.groovy
Labels: J: Format Test Failure

#635 Selected File Extensions
  include/inviwo/core/io/datareaderfactory.h
  include/inviwo/core/properties/fileproperty.h
  include/inviwo/core/properties/optionproperty.h
  include/inviwo/core/util/filedialog.h
  include/inviwo/core/util/fileextension.h
  modules/base/include/modules/base/processors/datasource.h
  modules/base/include/modules/base/processors/imagesource.h
  modules/base/include/modules/base/processors/volumesequencesource.h
  modules/base/include/modules/base/processors/volumesource.h
  modules/base/src/processors/imagesource.cpp
  modules/base/src/processors/volumesequencesource.cpp
  modules/base/src/processors/volumesource.cpp
  modules/hdf5/include/modules/hdf5/processors/hdf5volumesource.h
  modules/json/src/jsonmodule.cpp
  modules/qtwidgets/include/modules/qtwidgets/inviwofiledialog.h
  modules/qtwidgets/src/inviwofiledialog.cpp
  modules/qtwidgets/src/properties/filepropertywidgetqt.cpp
  modules/qtwidgets/src/qtwidgetsmodule.cpp
  modules/webbrowser/include/modules/webbrowser/processors/webbrowserprocessor.h
  src/core/properties/fileproperty.cpp
  src/core/util/fileextension.cpp
Labels: J: Format Test Failure

#632 Core: Make PropertyOwner remove all its properties before destruction…
  include/inviwo/core/processors/canvasprocessor.h
  include/inviwo/core/properties/property.h
  include/inviwo/core/properties/propertyowner.h
  modules/basegl/include/modules/basegl/processors/multichannelraycaster.h
  modules/basegl/src/processors/multichannelraycaster.cpp
  modules/pvm/CMakeLists.txt
  src/core/processors/canvasprocessor.cpp
  src/core/properties/property.cpp
  src/core/properties/propertyowner.cpp
Labels: J: Format Test Failure, T: Bug

#643 Observable fix
  include/inviwo/core/properties/tfpropertyconcept.h
  include/inviwo/core/util/observer.h
  modules/pvm/src/pvmvolumereader.cpp
  src/core/datastructures/tfprimitiveset.cpp
Labels: J: Format Test Failure

#644 OpenGL: Print correct file when having glsl link errors
  modules/opengl/src/shader/shader.cpp
Labels: J: Format Test Failure

#645 OpenGLQT: Issue a resize event after making canvas visible to ensure correct size, closes #536
  modules/openglqt/src/canvasprocessorwidgetqt.cpp
Labels: J: Format Test Failure

#648 Minmax property fix
  include/inviwo/core/properties/minmaxproperty.h
  include/inviwo/core/properties/templateproperty.h
Labels: J: Format Test Failure

#601 fix sigar not building on linux
  cmake/modules/FindTIRPC.cmake
  ext/sigar/CMakeLists.txt
  ext/sigar/src/os/linux/linux_sigar.c
Labels: J: Format Test Failure

#650 Python3: pybind fix for TFPrimitiveSet
  modules/python3/bindings/src/pytfprimitiveset.cpp
Labels: J: Format Test Failure

#637 CMake: Grouping modules in folders #513
  cmake/globalmacros.cmake
  modules/meta.cmake
Labels: J: Format Test Failure

#653 Feature/line tracing cleanup
  modules/base/include/modules/base/algorithm/randomutils.h
  modules/vectorfieldvisualization/include/modules/vectorfieldvisualization/integrallinetracer.h
  modules/vectorfieldvisualization/src/processors/datageneration/seedpointgenerator.cpp
  modules/vectorfieldvisualizationgl/tests/regression/streamlinescolorby/coloronport.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinescolorby/constant.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinescolorby/curvature.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinescolorby/streamlinescolorby.inv
  modules/vectorfieldvisualizationgl/tests/regression/streamlinescolorby/velocity.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesdirections/bidir.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesdirections/bwd.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesdirections/fwd.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesdirections/streamlinesdirections.inv
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesintegrationscheme/euler.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesintegrationscheme/rk4.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesintegrationscheme/streamlinesintegrationscheme.inv
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesseedingspace/dataspace.png
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesseedingspace/streamlinesseedingspace.inv
  modules/vectorfieldvisualizationgl/tests/regression/streamlinesseedingspace/worldspace.png
Labels: J: Format Test Failure

#654 Feature/welcomewidget
  include/inviwo/qt/editor/filetreemodel.h
  include/inviwo/qt/editor/filetreewidget.h
  include/inviwo/qt/editor/welcomewidget.h
  resources/changelog.html
  resources/inviwo.qrc
  resources/svgicons/lineedit-clear-active.svg
  resources/svgicons/lineedit-clear.svg
  src/qt/editor/CMakeLists.txt
  src/qt/editor/filetreemodel.cpp
  src/qt/editor/filetreewidget.cpp
  src/qt/editor/inviwomainwindow.cpp
  src/qt/editor/processorlistwidget.cpp
  src/qt/editor/welcomewidget.cpp
Labels: J: Format Test Failure

#649 PlottingGL: Possible to specify margins including labels for Parallel…
  CHANGELOG.md
  modules/plottinggl/data/workspaces/parallelcoordinates.inv
  modules/plottinggl/include/modules/plottinggl/processors/parallelcoordinates/parallelcoordinates.h
  modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
  modules/plottinggl/tests/regression/parallelcoordinates/Canvas.png
  modules/plottinggl/tests/regression/pcp-inverted-axis/Canvas.png
  modules/plottinggl/tests/regression/pcp-inverted-axis/config.json
  modules/plottinggl/tests/regression/pcp-no-handles/Canvas.png
  modules/plottinggl/tests/regression/pcp-no-handles/config.json
  modules/plottinggl/tests/regression/pcp-with-labels/Canvas.png
  modules/plottinggl/tests/regression/pcp-with-labels/pcp-with-labels.inv
  resources/changelog.html
Labels: J: Format Test Failure

#655 Webbrowser: Select sync fix. Old options where not removed before.
  modules/webbrowser/data/js/inviwoapi.js
Labels: J: Format Test Failure

#661 Feature/volumereader
  ext/ticpp/tinyxml.cpp
  include/inviwo/core/io/rawvolumereader.h
  include/inviwo/core/io/volumedatareaderdialog.h
  modules/base/include/modules/base/io/datvolumesequencereader.h
  modules/base/include/modules/base/io/ivfsequencevolumereader.h
  modules/base/include/modules/base/io/ivfvolumereader.h
  modules/base/src/io/datvolumesequencereader.cpp
  modules/base/src/io/datvolumewriter.cpp
  modules/base/src/io/ivfvolumereader.cpp
  modules/base/src/io/ivfvolumewriter.cpp
  modules/qtwidgets/include/modules/qtwidgets/rawdatareaderdialogqt.h
  modules/qtwidgets/src/rawdatareaderdialogqt.cpp
  src/core/io/rawvolumereader.cpp
Labels: J: Format Test Failure

#662 Qt: improved welcome widget filtering
  include/inviwo/qt/editor/filetreemodel.h
  include/inviwo/qt/editor/filetreewidget.h
  resources/changelog.html
  src/qt/editor/filetreemodel.cpp
  src/qt/editor/filetreewidget.cpp
  src/qt/editor/welcomewidget.cpp
Labels: J: Format Test Failure

#668 Qt: warn fix
  src/qt/editor/filetreewidget.cpp
Labels: J: Format Test Failure

#665 D&D fix
  modules/base/include/modules/base/processors/datasource.h
  modules/base/src/processors/imagesource.cpp
  modules/base/src/processors/volumesequencesource.cpp
  modules/base/src/processors/volumesource.cpp
Labels: J: Format Test Failure

#664 Feature/various
  include/inviwo/core/util/foreach.h
  include/inviwo/core/util/stdextensions.h
  modules/base/src/processors/surfaceextractionprocessor.cpp
  modules/base/src/properties/basisproperty.cpp
  modules/dataframe/src/properties/dataframeproperty.cpp
  modules/plottinggl/src/processors/colorscalelegend.cpp
  modules/python3/src/pythoninterpreter.cpp
  modules/qtwidgets/src/codeedit.cpp
  modules/qtwidgets/src/properties/buttongrouppropertywidgetqt.cpp
  modules/webbrowser/src/renderhandlergl.cpp
  src/core/properties/property.cpp
  src/core/properties/propertyowner.cpp
  src/core/properties/tfpropertyconcept.cpp
Labels: J: Format Test Failure

#672 Core: IndexMapper: Fix for incorrect operand order when converting 1D linear-index to 2D coords
  include/inviwo/core/util/indexmapper.h
Labels: J: Format Test Failure

#675 Python3: exposing Image constructor from a Layer
  modules/python3/bindings/src/pyimage.cpp
Labels: J: Format Test Failure

#670 External libs
  CMakeLists.txt
  cmake/licenses.cmake
  ext/libjpeg/CMakeLists.txt
  ext/libpng/CMakeLists.txt
  ext/tiff/libtiff/CMakeLists.txt
  modules/cimg/CMakeLists.txt
  modules/cimg/src/cimgutils.cpp
  modules/hdf5/CMakeLists.txt
  modules/nifti/ext/nifticlib-2.0.0/niftilib/CMakeLists.txt
  modules/nifti/ext/nifticlib-2.0.0/znzlib/CMakeLists.txt
  modules/png/CMakeLists.txt
  src/core/CMakeLists.txt
  src/qt/editor/CMakeLists.txt
Labels: J: Format Test Failure

#676 Feature/python3fix
  modules/python3/bindings/src/pyproperties.cpp
Labels: P: Python
