Repository inviwo/inviwo, pull requests merged in 2019-09, with the labels that each got.

#673 Update required Qt version to 5.12
  src/qt/editor/CMakeLists.txt
Labels: J: Format Test Failure, T: Bug

#597 Guides, please review me
  docs/markdown/DevGuide_Meta.md
  docs/markdown/GettingStarted_Build.md
  docs/markdown/GettingStarted_Network.md
  docs/markdown/GettingStarted_UI.md
  docs/markdown/images/DataStructures.png
  docs/markdown/images/NetworkExplained.png
  docs/markdown/images/PortInspector.png
  docs/markdown/images/Processor.png
  docs/markdown/images/PropertyLinks.png
  docs/markdown/images/PropertySemanticsColor.png
  docs/markdown/images/PropertySemanticsLightpos.png
  docs/markdown/images/PropertySemanticsMerged.png
  docs/markdown/images/PropertySemanticsSlider.png
  docs/markdown/images/PropertySemanticsSpherical.png
  docs/markdown/images/UI.png
Labels: P: Documentation

#685 PostProcessing: Replaced ImageSharpen with ImageFilter processor
  modules/basegl/include/modules/basegl/algorithm/imageconvolution.h
  modules/basegl/src/algorithm/imageconvolution.cpp
  modules/postprocessing/CMakeLists.txt
  modules/postprocessing/glsl/imagesharpen.frag
  modules/postprocessing/include/modules/postprocessing/processors/imagefilter.h
  modules/postprocessing/src/postprocessingmodule.cpp
  modules/postprocessing/src/processors/imagefilter.cpp
  modules/postprocessing/src/processors/imagesharpen.cpp
  tools/jenkins/check-format.py
Labels: T: Feature

#699 Feature/reset2
  Jenkinsfile
  include/inviwo/core/properties/cameraproperty.h
  include/inviwo/core/properties/minmaxproperty.h
  include/inviwo/core/properties/optionproperty.h
  include/inviwo/core/properties/ordinalproperty.h
  include/inviwo/core/properties/templateproperty.h
  include/inviwo/core/properties/valuewrapper.h
  src/core/properties/cameraproperty.cpp
  src/core/properties/compositeproperty.cpp
  tools/jenkins/check-format.py
  tools/jenkins/util.groovy
Labels: J: Auto Format

#707 Feature/tfeditor
  modules/qtwidgets/include/modules/qtwidgets/numberlineedit.h
  modules/qtwidgets/include/modules/qtwidgets/properties/colorlineedit.h
  modules/qtwidgets/include/modules/qtwidgets/properties/doublevaluedragspinbox.h
  modules/qtwidgets/include/modules/qtwidgets/tf/tfcoloredit.h
  modules/qtwidgets/include/modules/qtwidgets/tf/tflineedit.h
  modules/qtwidgets/src/numberlineedit.cpp
  modules/qtwidgets/src/properties/colorlineedit.cpp
  modules/qtwidgets/src/properties/doublevaluedragspinbox.cpp
  modules/qtwidgets/src/tf/tfcoloredit.cpp
  modules/qtwidgets/src/tf/tflineedit.cpp
  modules/qtwidgets/src/tf/tfpropertydialog.cpp
Labels: J: Auto Format

#710 Added auto save and restore support
  include/inviwo/qt/editor/inviwomainwindow.h
  include/inviwo/qt/editor/undomanager.h
  src/qt/editor/inviwomainwindow.cpp
  src/qt/editor/undomanager.cpp
  src/qt/editor/welcomewidget.cpp
Labels: J: Auto Format

#709 FontRendering/PlottingGL: Bug fixes to prevent errors due to string w…
  modules/fontrendering/src/textrenderer.cpp
  modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
Labels: J: Auto Format

#712 Input-selection
  include/inviwo/core/interaction/events/event.h
  include/inviwo/core/network/networkutils.h
  include/inviwo/core/network/processornetworkevaluator.h
  include/inviwo/core/ports/inport.h
  include/inviwo/core/processors/processor.h
  include/inviwo/core/processors/processorobserver.h
  modules/base/include/modules/base/processors/inputselector.h
  modules/webbrowser/src/webbrowserapp.cpp
  src/core/interaction/events/event.cpp
  src/core/network/networkutils.cpp
  src/core/network/processornetworkevaluator.cpp
  src/core/ports/inport.cpp
  src/core/processors/processor.cpp
Labels: J: Auto Format

#713 Feature/qt gl fixes
  modules/opengl/include/modules/opengl/canvasprocessorgl.h
  modules/opengl/src/canvasprocessorgl.cpp
  modules/openglqt/src/canvasqglwidget.cpp
  modules/png/src/pngreader.cpp
  src/qt/applicationbase/inviwoapplicationqt.cpp
  src/qt/editor/inviwomainwindow.cpp
Labels: J: Auto Format

#718 BaseGL: ImageLayout deactive zero-sized layout elements to prevent Op…
  modules/basegl/include/modules/basegl/processors/imageprocessing/imagelayoutgl.h
  modules/basegl/src/processors/imageprocessing/imagelayoutgl.cpp
Labels: J: Auto Format

#725 Jenkins: Use inviwo team user as authorwhen commiting auto format
  tools/jenkins/check-format.py
Labels: P: Jenkins, T: For discussion

#722 ImageLayoutGL: Use proper error message in assertion
  modules/basegl/src/processors/imageprocessing/imagelayoutgl.cpp
Labels: J: Auto Format

#733 Feature/dataframepython
  modules/dataframepython/CMakeLists.txt
  modules/dataframepython/bindings/CMakeLists.txt
  modules/dataframepython/bindings/include/ivwdataframe/ivwdataframe.h
  modules/dataframepython/bindings/include/ivwdataframe/pydataframe.h
  modules/dataframepython/bindings/src/ivwdataframe.cpp
  modules/dataframepython/bindings/src/pydataframe.cpp
  modules/dataframepython/depends.cmake
  modules/dataframepython/include/inviwo/dataframepython/dataframepythonmodule.h
  modules/dataframepython/include/inviwo/dataframepython/dataframepythonmoduledefine.h
  modules/dataframepython/readme.md
  modules/dataframepython/src/dataframepythonmodule.cpp
  modules/dataframepython/tests/unittests/column-test.cpp
  modules/dataframepython/tests/unittests/dataframe-test.cpp
  modules/dataframepython/tests/unittests/dataframepython-unittest-main.cpp
Labels: J: Auto Format
