Repository inviwo/inviwo, pull requests merged in 2019-03, with the labels that each got.

#444 QtWidgets: TF preview high-dpi fix, closes #443
  modules/qtwidgets/src/tf/tfutils.cpp
  resources/stylesheets/inviwo.qss
Labels: J: Format Test Failure

#452 Feature/variousfixes
  include/inviwo/core/util/stdextensions.h
  src/qt/editor/inviwomainwindow.cpp
Labels: J: Format Test Failure

#457 PlottingGL: Changed to use value range instead of data range in color scale.
  modules/plottinggl/include/modules/plottinggl/processors/colorscalelegend.h
  modules/plottinggl/src/processors/colorscalelegend.cpp
Labels: J: Format Test Failure

#454 Qt: Fix for Processor eval time not being reseted
  src/qt/editor/processorgraphicsitem.cpp
Labels: J: Format Test Failure

#456 Testing: CMake fix, #445
  tests/testutil/CMakeLists.txt
Labels: J: Format Test Failure

#453 BrushingAndLinking: Fixed a bug where the column selection would not …
  modules/brushingandlinking/src/ports/brushingandlinkingports.cpp
Labels: J: Format Test Failure

#422 Two Axis Valuator Trackball
  include/inviwo/core/interaction/trackball.h
  include/inviwo/core/util/settings/systemsettings.h
  src/core/interaction/trackball.cpp
  src/core/util/settings/systemsettings.cpp
Labels: J: Format Test Failure, T: Feature, T: For discussion

#458 Beautify Property api
  include/inviwo/core/properties/property.h
  include/inviwo/core/properties/propertyowner.h
Labels: J: Format Test Failure, T: For discussion

#468 Added link to slack in readme
  README.md
Labels: J: Format Test Failure

#466 General: fixed typo `util::PrecsionType`/`util::PrecsionValueType`
  include/inviwo/core/datastructures/buffer/bufferram.h
  include/inviwo/core/datastructures/image/layerram.h
  include/inviwo/core/datastructures/volume/volumeram.h
  include/inviwo/core/util/formatdispatching.h
  modules/base/include/modules/base/algorithm/image/layerramdistancetransform.h
  modules/base/include/modules/base/algorithm/image/layerramsubset.h
  modules/base/include/modules/base/algorithm/volume/volumeramdistancetransform.h
  modules/base/src/algorithm/image/layerramsubset.cpp
  modules/base/src/algorithm/volume/marchingcubes.cpp
  modules/base/src/algorithm/volume/marchingcubesopt.cpp
  modules/base/src/algorithm/volume/marchingtetrahedron.cpp
  modules/base/src/algorithm/volume/volumecurl.cpp
  modules/base/src/algorithm/volume/volumedivergence.cpp
  modules/base/src/algorithm/volume/volumeramsubsample.cpp
  modules/base/src/algorithm/volume/volumesignificantvoxels.cpp
  modules/base/src/processors/imagestackvolumesource.cpp
  modules/base/src/processors/volumeslice.cpp
  modules/hdf5/src/datastructures/hdf5handle.cpp
  modules/plotting/src/datastructures/dataframe.cpp
  modules/plotting/src/datastructures/dataframeutil.cpp
  modules/plotting/src/processors/dataframeexporter.cpp
  modules/plotting/src/processors/imagetodataframe.cpp
  modules/plotting/src/processors/volumetodataframe.cpp
  src/core/datastructures/buffer/bufferram.cpp
Labels: J: Format Test Failure

#469 CMake: truncate module tooltips
  cmake/globalmacros.cmake
Labels: J: Format Test Failure

#464 Feature/various
  modules/eigenutils/CMakeLists.txt
  modules/eigenutils/include/modules/eigenutils/eigenutils.h
  modules/eigenutils/include/modules/eigenutils/processors/testmatrix.h
  modules/eigenutils/src/eigenutilsmodule.cpp
  modules/eigenutils/src/processors/testmatrix.cpp
  modules/eigenutils/tests/regression/matrixtoimage/Canvas.png
  modules/eigenutils/tests/regression/matrixtoimage/Canvas2.png
  modules/eigenutils/tests/regression/matrixtoimage/matrixtoimage.inv
  modules/opengl/include/modules/opengl/clockgl.h
  modules/opengl/src/clockgl.cpp
  modules/qtwidgets/include/modules/qtwidgets/numberlineedit.h
  modules/qtwidgets/src/numberlineedit.cpp
Labels: J: Format Test Failure

#471 Various: warning fixes
  CMakeLists.txt
  cmake/pybind11.cmake
  include/inviwo/core/properties/propertyowner.h
  include/inviwo/core/util/singleton.h
  include/inviwo/qt/applicationbase/inviwoapplicationqt.h
  modules/webbrowser/src/renderhandlergl.cpp
  src/core/interaction/trackball.cpp
Labels: J: Format Test Failure

#470 pypickingmapper with new pickingevent enums/methods
  modules/python3/bindings/src/pypickingmapper.cpp
  modules/python3/bindings/src/pyproperties.cpp
Labels: J: Format Test Failure
