Repository inviwo/inviwo, pull requests merged in 2020-04, with the labels that each got.

#922 Core: Threadpool: Prevent SetThreadDescription runtime error on Windows Server 2016
  include/inviwo/core/util/threadutil.h
  src/core/CMakeLists.txt
  src/core/util/threadpool.cpp
  src/core/util/threadutil.cpp
  src/core/util/timer.cpp
Labels: J: Auto Format

#927 Fix/remove warnings
  include/inviwo/core/processors/poolprocessor.h
  include/inviwo/core/processors/processorfactoryobject.h
  modules/plottinggl/src/processors/parallelcoordinates/parallelcoordinates.cpp
  modules/python3/bindings/src/pyimage.cpp
  src/core/datastructures/camera.cpp
Labels: J: Format Test Failure, J: Regression Test Failure

#924 DataFrame: Make ColorMapProperty default to diverging color map if va…
  modules/dataframe/src/properties/colormapproperty.cpp
Labels: J: Auto Format, J: Format Test Failure

#929 exposed evaluate when hidden in the canvas processor
  include/inviwo/core/processors/canvasprocessor.h
  src/core/processors/canvasprocessor.cpp
Labels: J: Format Test Failure
