Repository inviwo/inviwo, pull requests merged in 2020-01, with the labels that each got.

#819 Add constexpr_hash overload for std::string_view
  include/inviwo/core/util/constexprhash.h
Labels: J: Auto Format

#816 Docs/guides
  docs/images/sponsors-merged.png
  docs/markdown/DevGuide_BuildProcessor.md
  docs/markdown/DevGuide_BuildProperty.md
  docs/markdown/DevGuide_Data_Memory.md
  docs/markdown/DevGuide_InviwoPy.md
  docs/markdown/DevGuide_PythonProcessors.md
  docs/markdown/images/mesh_bb_render_workspace.png
Labels: P: Documentation

#823 ShaderSegements
  modules/opengl/CMakeLists.txt
  modules/opengl/glsl/utils/raycastgeometry.glsl
  modules/opengl/glsl/utils/sampler3d.glsl
  modules/opengl/include/modules/opengl/shader/linenumberresolver.h
  modules/opengl/include/modules/opengl/shader/shaderobject.h
  modules/opengl/include/modules/opengl/shader/shadersegment.h
  modules/opengl/src/shader/linenumberresolver.cpp
  modules/opengl/src/shader/shaderobject.cpp
  modules/opengl/src/shader/shadersegment.cpp
  modules/opengl/src/shader/shaderutils.cpp
  modules/opengl/tests/unittests/opengl-unittest-main.cpp
  modules/opengl/tests/unittests/shaderobject-test.cpp
Labels: J: Auto Format, J: Format Test Failure

#824 Webbrowser: Fix for non-mac systems due to latest CEF updates
  modules/webbrowser/src/webbrowsermodule.cpp
  modules/webbrowser/webhelper/CMakeLists.txt
Labels: J: Auto Format

#835 CMake: Make the changelog project optional (on by default)
  src/qt/editor/CMakeLists.txt
Labels: J: Auto Format

#849 Mesh and Shader fixes
  modules/base/include/modules/base/algorithm/meshutils.h
  modules/basegl/include/modules/basegl/processors/meshrenderprocessorgl.h
  modules/basegl/src/processors/meshrenderprocessorgl.cpp
  modules/opengl/include/modules/opengl/buffer/bufferobject.h
  modules/opengl/include/modules/opengl/glformats.h
  modules/opengl/include/modules/opengl/shader/shaderobject.h
  modules/opengl/include/modules/opengl/texture/textureunit.h
  modules/opengl/src/buffer/bufferobject.cpp
  modules/opengl/src/shader/shaderobject.cpp
  modules/opengl/src/texture/texture.cpp
  modules/opengl/src/texture/textureunit.cpp
  modules/opengl/tests/unittests/shaderobject-test.cpp
  modules/openglqt/include/modules/openglqt/shaderwidget.h
Labels: J: Auto Format
