Repository inviwo/inviwo, pull requests merged in 2020-03, with the labels that each got.

#874 FormatDispatching: Remove Win32 macro
  include/inviwo/core/util/formatdispatching.h
Labels: J: Auto Format

#889 Base: DatVolumeSequenceReader fix for dat-file containing multiple fi…
  modules/base/src/io/datvolumesequencereader.cpp
Labels: T: Bug

#894 Feature/webbrowser touchevents
  modules/webbrowser/data/workspaces/web_property_sync.html
  modules/webbrowser/include/modules/webbrowser/interaction/cefinteractionhandler.h
  modules/webbrowser/src/interaction/cefinteractionhandler.cpp
  modules/webbrowser/src/processors/webbrowserprocessor.cpp
Labels: J: Auto Format

#896 Webbrowser: Added functionality to retrieve which processor is respon…
  CHANGELOG.md
  modules/webbrowser/data/js/inviwoapi.js
  modules/webbrowser/data/workspaces/web_property_sync.html
  modules/webbrowser/include/modules/webbrowser/processors/processorcefsynchronizer.h
  modules/webbrowser/include/modules/webbrowser/webbrowserclient.h
  modules/webbrowser/src/processors/processorcefsynchronizer.cpp
  modules/webbrowser/src/processors/webbrowserprocessor.cpp
  modules/webbrowser/src/properties/propertycefsynchronizer.cpp
  modules/webbrowser/src/webbrowserclient.cpp
Labels: J: Auto Format

#904 Core: DataOutport: Added method to move data into the port
  include/inviwo/core/ports/dataoutport.h
Labels: J: Auto Format, T: Feature

#908 Niftireader: Fixed data range bug introduced in #466a9ba
  modules/nifti/src/niftireader.cpp
Labels: J: Auto Format

#909 Feature/colormaps few colors
  include/inviwo/core/util/colorbrewer-generated.h
  modules/webbrowser/data/js/inviwoapi.js
  modules/webbrowser/src/processors/processorcefsynchronizer.cpp
  modules/webbrowser/src/properties/propertycefsynchronizer.cpp
  src/core/util/colorbrewer-generated.cpp
  tools/codegen/colorbrewer/colorbrewer.json
  tools/codegen/colorbrewer/colorbrewer.py
  tools/codegen/colorbrewer/colorbrewer_tmpl.cpp
Labels: J: Auto Format

#910 Core: VS 16.5.0 Warning fixes
  include/inviwo/core/common/inviwoapplication.h
  include/inviwo/core/datastructures/geometry/typedmesh.h
  include/inviwo/core/properties/property.h
  include/inviwo/core/util/stdextensions.h
  include/inviwo/core/util/stringconversion.h
  include/inviwo/core/util/threadpool.h
  modules/base/include/modules/base/algorithm/image/imagecontour.h
  modules/base/include/modules/base/algorithm/meshutils.h
  modules/qtwidgets/include/modules/qtwidgets/inviwoqtutils.h
  modules/qtwidgets/include/modules/qtwidgets/properties/colorpropertywidgetqt.h
  modules/qtwidgets/src/inviwoqtutils.cpp
  modules/qtwidgets/src/tf/tfpropertydialog.cpp
  src/core/io/tempfilehandle.cpp
  src/core/util/filesystem.cpp
  src/core/util/stringconversion.cpp
  src/qt/editor/processorlistwidget.cpp
Labels: J: Auto Format
